# Generated by Django 6.0.4 on 2026-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('card_machine', 'Card Machine'), ('epos_system', 'EPOS System'), ('business_energy', 'Business Energy'), ('business_water', 'Business Water'), ('broadband', 'Business Broadband')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
